[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src * data: blob:;
      script-src * 'unsafe-inline' 'unsafe-eval';
      connect-src * wss:;
      img-src * data:;
      style-src * 'unsafe-inline';
    """
